### ISSUE TITLE
README.md should be in markdown

### ISSUE THREAD

**Issue by nemchik** [thelounge/thelounge-docker#61]
https://hub.docker.com/r/thelounge/thelounge/

Docker Hub displays the readme incorrectly because HTML is used. README.md should be in markdown in order to display correctly.

**Comment by williamboman** [comment]
Thanks for the report! This is fixed in the `v3-docs` branch.

<blockquote>
The documentation for `v3` can be found at the `v3-docs` branch for now. The `master` branch in this repo currently holds documentation for the latest stable release, which is `2.7.1`.

I know this git repository does contain `3.0.0-pre`-releases, the reason for this is automated DockerHub builds. In retrospect, I should've pushed these releases to another branch than `master` to avoid confusion.

The docs will be in an awkward state until first stable `v3` is released due to a couple reasons:
 - we've renamed the Docker image from `thelounge/lounge` to `thelounge/thelounge`
    - `thelounge/lounge` will not receive any new images, the latest release it'll hold will be `2.7.1` (assuming we don't do another minor/patch release in the `v2` branch)
 - both these images are built off of automated builds from the same git repo (this one)
 - there are some breaking changes between the `v2` and `v3`-prerelease docker containers

I will update this git repository's documentation once `v3` is released.

I hope this clears things up!
</blockquote>

**Comment by williamboman** [comment]
With that said, I will manually update the docs over at the DockerHub repo for now. It's automatically updated when triggering an automated build - hence the HTML

**Comment by williamboman** [comment]
Also, PRs are welcome to improve docs. Both in terms of actual content as well as formatting (it's not the prettiest right now). Make sure to use `v3-docs` as base branch 😊
